import os
from dotenv import load_dotenv

load_dotenv()

# --- Zerodha Kite Connect ---
KITE_API_KEY = os.getenv("KITE_API_KEY")
KITE_API_SECRET = os.getenv("KITE_API_SECRET")
KITE_USER_ID = os.getenv("KITE_USER_ID")
KITE_PASSWORD = os.getenv("KITE_PASSWORD")
KITE_TOTP_SECRET = os.getenv("KITE_TOTP_SECRET")

# --- Twilio WhatsApp ---
TWILIO_ACCOUNT_SID = os.getenv("TWILIO_ACCOUNT_SID")
TWILIO_AUTH_TOKEN = os.getenv("TWILIO_AUTH_TOKEN")
TWILIO_WHATSAPP_FROM = os.getenv("TWILIO_WHATSAPP_FROM", "whatsapp:+14155238886")
USER_WHATSAPP_TO = os.getenv("USER_WHATSAPP_TO")

# --- Claude AI ---
ANTHROPIC_API_KEY = os.getenv("ANTHROPIC_API_KEY")

# --- App Config ---
FLASK_PORT = int(os.getenv("FLASK_PORT", "5000"))
DATABASE_PATH = os.getenv("DATABASE_PATH", "./data/trades.db")
WEBHOOK_URL = os.getenv("WEBHOOK_URL", "")

# --- Scanning Config ---
SCAN_INTERVAL_SECONDS = 300
SCAN_UNDERLYINGS = ["NIFTY", "BANKNIFTY"]
STRIKES_RANGE = 10
USE_AI_ANALYSIS = True

# --- Risk Management ---
MAX_LOSS_PER_TRADE = 2000
MAX_LOSS_PER_DAY = 5000
MAX_OPEN_POSITIONS = 2
MAX_CAPITAL_PERCENT_PER_TRADE = 0.05
MIN_RISK_REWARD_RATIO = 1.5
MIN_OPTION_PREMIUM = 50
MAX_BID_ASK_SPREAD_PERCENT = 2.0

# --- Exit Config ---
TRAILING_SL_TRIGGER_PERCENT = 50
TRAILING_SL_BREAKEVEN_PERCENT = 50
TRAILING_SL_PROFIT_LOCK_PERCENT = 75
MAX_HOLDING_MINUTES = 120
EOD_EXIT_TIME = "15:15"
EXPIRY_DAY_EXIT_TIME = "15:20"

# --- WhatsApp Config ---
TRADE_CONFIRMATION_TIMEOUT_SECONDS = 300
SEND_DAILY_SUMMARY = True
DAILY_SUMMARY_TIME = "15:35"

# --- Market Hours ---
MARKET_OPEN = "09:15"
MARKET_CLOSE = "15:30"
PRE_MARKET_LOGIN = "09:00"
SCAN_START = "09:20"
SCAN_END = "15:15"

# --- Charges ---
BROKERAGE_PER_ORDER = 20
STT_PERCENT_SELL = 0.0625
GST_PERCENT = 0.18
STAMP_DUTY_PERCENT = 0.003
SEBI_CHARGES_PERCENT = 0.0001
EXCHANGE_TXN_PERCENT = 0.00053
